unbind r
bind r source-file ~/.tmux.conf
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set -g prefix C-Space
bind C-Space send-prefix

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U

bind n new-window
bind c kill-window
bind q kill-session
bind l choose-tree -Zs
bind Right next-window
bind Left previous-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @dracula-plugins "weather"
set -g @dracula-fixed-location "Warsaw"
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @dracula-show-location false
set -g @dracula-show-fahrenheit false
set -g @dracula-show-battery-label false
set -g @dracula-show-battery-status true
set -g @dracula-show-flags true
set -g @dracula-battery-colors "default white"
set -g @dracula-weather-colors "default orange"
set -g @dracula-colors "default=default"
set -g @dracula-show-left-icon session
set -g @dracula-left-icon-padding 2
set -g @dracula-show-left-sep ' '
set -g @dracula-show-right-sep ' '
set -g @dracula-show-timezone false
set -g @dracula-show-date false
set -g @dracula-show-time false
set -g @resurrect-dir '~/.local/share/tmux/resurrect'
set -g @continuum-save-interval '10'
set -g status-position top

run '~/.tmux/plugins/tpm/tpm'

set -g status-style 'bg=default'
set -g status-left '#[fg=#ff9e64,bg=default,bold] #S '
set -g window-status-current-format '#[fg=#000000,bg=#ff9e64,bold] #I:#W '
set -g window-status-format '#[fg=#888888,bg=default] #I:#W '
