# Fish — Deep Indigo interactive environment

# Keep Ghostty integration when Fish is launched inside Zellij.
if status is-interactive; and set -q GHOSTTY_RESOURCES_DIR
    set -l ghostty_fish "$GHOSTTY_RESOURCES_DIR/shell-integration/fish/vendor_conf.d/ghostty-shell-integration.fish"
    test -f "$ghostty_fish"; and source "$ghostty_fish"
end

set -gx EDITOR nvim
set -gx VISUAL nvim
set -gx SHELL /usr/bin/fish
set -gx PAGER less
set -gx LESS '-R --mouse'
set -gx MANPAGER 'sh -c "col -bx | bat -l man -p"'

if status is-interactive
    set -g fish_greeting

    # Shell syntax colours are generated from ~/.config/theme/palette.toml
    # generated by ~/.config/theme/apply.py -- do not edit by hand
    set -g fish_color_normal dde2f0
    set -g fish_color_command eff3ff --bold
    set -g fish_color_keyword f2d79a
    set -g fish_color_quote 7fd6a8
    set -g fish_color_redirection 9adbe4
    set -g fish_color_end f2d79a
    set -g fish_color_error f2868f --bold
    set -g fish_color_param dde2f0
    set -g fish_color_comment 8f99bd --italics
    set -g fish_color_selection --background=eff3ff 1e2b57
    set -g fish_color_search_match --background=33407a eff3ff
    set -g fish_color_operator 9adbe4
    set -g fish_color_escape cbb2f5
    set -g fish_color_autosuggestion 8f99bd
    set -g fish_color_valid_path bcc9ff --underline
    # end generated

    # Interactive conveniences only; standard commands remain untouched.
    abbr -a -g ll 'eza --long --all --icons --group-directories-first --git'
    abbr -a -g la 'eza --all --icons --group-directories-first'
    abbr -a -g lt 'eza --tree --level=2 --icons --group-directories-first'
    abbr -a -g g git
    abbr -a -g gs 'git status --short --branch'
    abbr -a -g gd 'git diff'
    abbr -a -g gl 'git log --oneline --decorate --graph --all -20'
    abbr -a -g c clear

    # Reserve Ctrl+R for Atuin; fzf keeps Ctrl+T and Alt+C.
    set -gx FZF_CTRL_R_COMMAND ''
    set -gx FZF_DEFAULT_OPTS '--height=45% --layout=reverse --border=rounded --info=inline --prompt="❯ " --pointer="◆" --marker="✓" --color=bg+:#26345f,bg:#1e2b57,spinner:#bcc9ff,hl:#9adbe4,fg:#dde2f0,header:#9adbe4,info:#8f99bd,pointer:#bcc9ff,marker:#f2d79a,fg+:#eff3ff,prompt:#bcc9ff,hl+:#b2eaf1,border:#33407a'
    set -gx FZF_CTRL_T_OPTS '--walker-skip .git,node_modules,target,.venv --preview "bat --color=always --style=numbers --line-range=:300 {} 2>/dev/null" --bind "ctrl-/:change-preview-window(down|hidden|)"'

    mise activate fish | source
    zoxide init fish | source
    fzf --fish | source
    atuin init fish --disable-up-arrow | source
    if test "$TERM" != dumb
        starship init fish | source
        functions -q enable_transience; and enable_transience
    end
end
